version: '3'

services:
  olx:
    build:
      context: ./
      args:
        - NODE_ENV=development
    env_file:
      - ./.env
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/ecommerce
